### ISSUE TITLE
Figured out why my gloves didn't have set bonus

### ISSUE THREAD

**Issue by dpeart** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#47] opened 2024-01-26 14:38 UTC
If you have a weapon and gloves, the weapon gets the set bonuses. If you unequip the weapon the gloves won't have a set bonus.

If you then re-equip the gloves they get the set bonus.

If you then . . re-equip the weapon it takes the set bonus, but the cycle repeats

**Comment by Samuel-IH** [comment] 2024-01-26 15:38
This is a bug, but not a bug with GTS. Closing this here and reopening it elsewhere.

**Closed as completed by Samuel-IH** 2024-01-26 15:38 UTC
Labels: bug
