### ISSUE TITLE
Crafting Copper Coif sits and does nothing

### ISSUE THREAD

**Issue by ExtraneousVariable** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#14] opened 2024-01-09 05:02 UTC
**Your setup**
Device platform: desktop (Win, MacOS, Linux), or mobile (Android, iOS)
Game version: stable release or development release
Windows 10

**Describe the bug**
Attempting to craft Copper Coif, nothing happens.  Can add to queue, progress bar doesn't move.  Restarted, same issue.  Nothing happens.

**To Reproduce**
Try crafting Copper Coif.  Have 289/4 ingots, but nothing happens.

**Screenshots**
![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/44353338/488f0b03-32fc-4b96-ac67-5f2c8c649267)

**Comment by ExtraneousVariable** [comment] 2024-01-09 05:04
Same (lack of) behavior on Shields as well.  Have all the listed ingredients, but nothing happens.
![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/44353338/295e5894-f531-4a7e-aecc-4193c908ddbb)

**Comment by Samuel-IH** [comment] 2024-01-09 23:26
Closing as duplicate of https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/issues/13

**Closed as completed by Samuel-IH** 2024-01-09 23:26 UTC
Labels: bug, duplicate
