### ISSUE TITLE
There is a bug which causes the resource number to go up when crafting

### ISSUE THREAD

**Issue by BarchamMal** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#55] opened 2024-01-30 17:00 UTC
I seem to have found a bug which causes the ingredients list to output a negative number.
<img width="200" alt="image" src="https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/115943779/ae90f9db-dc8b-4c21-af02-1ef04044418f">
I have not found a way to reproduce this error but am opening this issue because I've seen it multiple times.
I will look for a way to reproduce the issue and will comment it if I find it.

**Comment by BarchamMal** [comment] 2024-01-30 19:52
I believe this is related to some bug which causes the number of raw to go up after crafting a gem.

**Comment by BarchamMal** [comment] 2024-01-30 20:00
I've found a way to reproduce the bug.
1. Queue up all of one type of raw gems in your inventory.
2. Wait for a bug which should bring the number up instead of down after crafting an item.
3. Add one more item to the queue.
4. Soon the number will be -1/1

**Comment by BarchamMal** [comment] 2024-01-30 20:01
I'm Hijacking this issue.

**Comment by Samuel-IH** [comment] 2024-01-31 18:12
Yep, the negative number part is not the issue here. That's simply what happens when you claim more recourses than you have.

The fact that the counter goes up by 1 when it shouldn't though, that's a bug.

**Comment by Samuel-IH** [comment] 2024-03-02 04:25
I'm unable to reproduce this. If it sits to long I'll be closing this bug as stale.
(made some big changes to the item tracking system since this issue was raised, may have inadvertently fixed it)

**Comment by BarchamMal** [comment] 2024-03-03 02:49
That's cool.
Haven't played the Alpha for a while, but if I do, I will try to reproduce it.

**Comment by dpeart** [comment] 2024-03-12 14:07
I reproduced this issue while cutting gems.

If you fail at cutting a gem it increases your raw materials by one.  Fail 4 times you now have 4 raw opals.  Add those back into the queue to craft.  On your next success your raw materials go negative.  If you fail again it will decrease the negative value by one.  Rinse and repeat.

I am current at -4/1 Raw Opal.  We'll see what happens when I empty the queue (17 to go)

It completed and I have -4/1 Raw Opals left.

**Comment by BarchamMal** [comment] 2024-03-12 16:34
Thank you @dpeart, I just tried this and it works. It only seems to happen with gems, (maybe cause they're the only crafts that require 1 ingredient?) which is odd, though this proves that the bug is not fixed. Now @Samuel-IH won't be closing this bug as stale and maybe it can be fixed. Either way, you can't get extra cut gems from it, it only tries to craft Nothing into Nothing.

**Comment by Samuel-IH** [comment] 2024-03-13 00:38
Thank you both of you for helping me reproduce this issue. It is fixed now.

**Closed as completed by Samuel-IH** 2024-03-13 00:38 UTC
Labels: bug
