### ISSUE TITLE
Yellow and Blue boots have the same stats

### ISSUE THREAD

**Issue by dpeart** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#45] opened 2024-01-26 14:17 UTC
![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/5182846/51d0c8c3-33bf-4063-aa8e-2a2050fee6de)

![image](https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/assets/5182846/4ea87eba-7807-4ccd-81d1-e1062d23762f)

**Comment by dpeart** [comment] 2024-01-26 14:28
Gold and Silver are the same as well

**Comment by Samuel-IH** [comment] 2024-01-26 15:46
Dupe of https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/issues/25

**Closed as not planned by Samuel-IH** 2024-01-26 15:46 UTC
Labels: bug
