### ISSUE TITLE
No smelting ironcold ores

### ISSUE THREAD

**Issue by Ilverostasone** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#27] opened 2024-01-09 20:00 UTC
I cant smelt ironcold ores on the forge,i Also tried to grt the maximum temperature,still nothing happens

**Comment by Samuel-IH** [comment] 2024-01-09 23:27
Closing as duplicate of https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/issues/8

**Closed as completed by Samuel-IH** 2024-01-09 23:27 UTC
Labels: bug
